service_out_of_memes:
  en: |-
    ğŸš€ You've watched all the memes we've prepared for you! Come back tomorrow for MORE. ğŸ”
  ru: |-
    ğŸš€ Ğ¢Ñ‹ Ğ¿Ğ¾ÑĞ¼Ğ¾Ñ‚Ñ€ĞµĞ» Ğ²ÑĞµ Ğ¼ĞµĞ¼Ñ‹, ĞºĞ¾Ñ‚Ğ¾Ñ€Ñ‹Ğµ Ğ¼Ñ‹ Ğ¿Ğ¾Ğ´Ğ³Ğ¾Ñ‚Ğ¾Ğ²Ğ¸Ğ»Ğ¸ Ğ´Ğ»Ñ Ñ‚ĞµĞ±Ñ! ĞŸÑ€Ğ¸Ñ…Ğ¾Ğ´Ğ¸ Ğ·Ğ°Ğ²Ñ‚Ñ€Ğ°, Ğ¿Ğ¾ĞºĞ°Ğ¶ĞµĞ¼ Ğ•Ğ©Ğ•. ğŸ”
  uk: |-
    ğŸš€ Ğ¢Ğ¸ Ğ¿ĞµÑ€ĞµĞ³Ğ»ÑĞ½ÑƒĞ² Ğ²ÑÑ– Ğ¼ĞµĞ¼Ğ¸, ÑĞºÑ– Ğ¼Ğ¸ Ğ¿Ñ–Ğ´Ğ³Ğ¾Ñ‚ÑƒĞ²Ğ°Ğ»Ğ¸ Ğ´Ğ»Ñ Ñ‚ĞµĞ±Ğµ! ĞŸÑ€Ğ¸Ñ…Ğ¾Ğ´ÑŒ Ğ·Ğ°Ğ²Ñ‚Ñ€Ğ°, Ğ¿Ğ¾ĞºĞ°Ğ¶ĞµĞ¼Ğ¾ Ğ‘Ğ†Ğ›Ğ¬Ğ¨Ğ•. ğŸ”
  ar: |-
    ğŸš€ Ø´Ø§Ù‡Ø¯Øª Ø¬Ù…ÙŠØ¹ Ø§Ù„ØµÙˆØ± Ø§Ù„Ù…Ø¶Ø­ÙƒØ© Ø§Ù„ØªÙŠ Ù‚Ù…Ù†Ø§ Ø¨ØªØ­Ø¶ÙŠØ±Ù‡Ø§ Ù„Ùƒ! Ø¹Ø¯ ØºØ¯Ù‹Ø§ Ù„Ù„Ù…Ø²ÙŠØ¯. ğŸ”
  es: |-
    ğŸš€ Â¡Has visto todos los memes que hemos preparado para ti! Vuelve maÃ±ana para MÃS. ğŸ”
  pt: |-
    ğŸš€ VocÃª viu todos os memes que preparamos para vocÃª! Volte amanhÃ£ para MAIS. ğŸ”
  fr: |-
    ğŸš€ Tu as regardÃ© tous les memes que nous avons prÃ©parÃ©s pour toi! Reviens demain pour PLUS. ğŸ”
  de: |-
    ğŸš€ Du hast alle Memes gesehen, die wir fÃ¼r dich vorbereitet haben! Komm morgen wieder fÃ¼r MEHR. ğŸ”
  it: |-
    ğŸš€ Hai visto tutti i meme che abbiamo preparato per te! Torna domani per ALTRO. ğŸ”
  pl: |-
    ğŸš€ ObejrzaÅ‚eÅ› wszystkie memy, ktÃ³re dla ciebie przygotowaliÅ›my! WrÃ³Ä‡ jutro po WIÄ˜CEJ. ğŸ”
