service.out_of_memes:
  en: |-
    ๐ You've watched all the memes we've prepared for you! 
    
    Come back tomorrow for MORE or add more languages: /lang. ๐
  ru: |-
    ะะะะซ ะะ ะกะะะะะะฏ ะะะะะะงะะะะกะฌ 
    
    ะัะธัะพะดะธ ะทะฐะฒััะฐ ะทะฐ ะฝะพะฒะพะน ะฟะพััะธะตะน ะธะปะธ ะดะพะฑะฐะฒั ะฑะพะปััะต ัะทัะบะพะฒ: /lang. ๐
  uk: |-
    ะะะะ ะะ ะกะฌะะะะะะ ะะะะะะงะะะะกะฌ 
    
    ะัะธัะพะดั ะทะฐะฒััะฐ ะทะฐ ะฝะพะฒะพั ะฟะพััััั ะฐะฑะพ ะดะพะดะฐะน ะฑัะปััะต ะผะพะฒ: /lang. ๐
  es: |-
    ๐ ยกHas visto todos los memes que hemos preparado para ti! 
    
    Vuelve maรฑana para MรS o agrega mรกs idiomas: /lang. ๐
  pt-br: |-
    ๐ Vocรช viu todos os memes que preparamos para vocรช! 
    
    Volte amanhรฃ para MAIS ou adicione mais idiomas: /lang. ๐
  fr: |-
    ๐ Tu as vu tous les memes que nous avons prรฉparรฉs pour toi! 
    
    Reviens demain pour PLUS ou ajoute plus de langues: /lang. ๐
  it: |-
    ๐ Hai visto tutti i meme che abbiamo preparato per te! 
    
    Torna domani per ALTRO o aggiungi piรน lingue: /lang. ๐
  de: |-
    ๐ Du hast alle Memes gesehen, die wir fรผr dich vorbereitet haben! 
    
    Komm morgen wieder fรผr MEHR oder fรผge mehr Sprachen hinzu: /lang. ๐
  tr: |-
    ๐ Senin iรงin hazฤฑrladฤฑฤฤฑmฤฑz tรผm memeleri izledin! 
    
    YARIN DAHA FAZLASI iรงin geri gel veya daha fazla dil ekle: /lang. ๐
  fa: |-
    ๐ ุชูุงู ููโูุง ฺฉู ุจุฑุง ุดูุง ุขูุงุฏู ฺฉุฑุฏูโุงู ุฑุง ุฏุฏูโุงุฏ! 
    
    ูุฑุฏุง ุจุฑุง ุจุดุชุฑ ุจุฑฺฏุฑุฏุฏ ุง ุฒุจุงูโูุง ุจุดุชุฑ ุงุถุงูู ฺฉูุฏ: /lang. ๐
  uz: |-
    ๐ Siz uchun tayyorlagan barcha memlarni ko'rdingiz! 
    
    ERTAGI KO'PROQ uchun qayting yoki ko'proq tillar qo'shing: /lang. ๐
  ar: |-
    ๐ ููุฏ ุดุงูุฏุช ุฌููุน ุงูุตูุฑ ุงูููุทูุฉ ุงูุชู ูููุง ุจุฅุนุฏุงุฏูุง ูู! 
    
    ุนุฏ ุบุฏูุง ูููุฒูุฏ ุฃู ุฃุถู ุงููุฒูุฏ ูู ุงููุบุงุช: /lang. ๐
  hi: |-
    ๐ เคเคชเคจเฅ เคเฅเคเฅเคธ เคฆเฅเค เคฒเคฟเค เคนเฅเค เคเฅ เคนเคฎเคจเฅ เคเคชเคเฅ เคฒเคฟเค เคคเฅเคฏเคพเคฐ เคเคฟเค เคนเฅเค! 
    
    เคเคฒ เคตเคพเคชเคธ เคเคเค เคเคฐ เคเคงเคฟเค เคฆเฅเคเฅเค เคฏเคพ เคเคงเคฟเค เคญเคพเคทเคพเคเค เคเฅเคกเคผเฅเค: /lang. ๐
  